### ISSUE TITLE
Als toernooiorganisator wil ik graag dat voor het bepalen van de eindstand het IJSCO (OSBO) reglement wordt toegepast.

### ISSUE THREAD

**Issue by oxygenius** [lmeulen/IJSCO_UI#10]
Er zou een IJSCO / OSBO reglement moeten worden opgesteld (en op de website geplaatst) en die moet worden toegepast in de software.

**Comment by lmeulen** [comment]
Wie heeft toegang tot deze regels en kan deze hier eenduidig opsommen?

**Comment by oxygenius** [comment]
Ik denk dat Peter er iets over kan zeggen en dat ik die dan vervolgens zal gaan formaliseren.
